project_id = "hnkyeohwjcqhgulgdydd"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.signup-with-pin]
verify_jwt = false

[functions.login-with-pin]
verify_jwt = false

[functions.create-employee-user]
verify_jwt = true