project_id = "hnkyeohwjcqhgulgdydd"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.signup-with-pin]
verify_jwt = false

[functions.login-with-pin]
verify_jwt = false

[functions.create-employee-user]
verify_jwt = true

[functions.submit-wishlist]
verify_jwt = false

[functions.wishlist-shop-info]
verify_jwt = false

[functions.customer-wishlist-login]
verify_jwt = false

[functions.customer-wishlist-history]
verify_jwt = false

[functions.customer-wishlist-resend]
verify_jwt = false

[functions.save-wishlist-template]
verify_jwt = false
[functions.marketplace-public]
verify_jwt = false

[functions.voice-to-fordo]
verify_jwt = false

[functions.parse-fordo-image]
verify_jwt = false

[functions.recharge-create-payment]
verify_jwt = true

[functions.recharge-verify-payment]
verify_jwt = true

[functions.seed-bd-geo]
verify_jwt = true

[functions.find-shops-by-phone]
verify_jwt = false

[functions.find-shops-by-name]
verify_jwt = false

[functions.customer-create-wishlist]
verify_jwt = true

[functions.customer-dispatch-fordo-schedules]
verify_jwt = false

[functions.consumer-fordo-history]
verify_jwt = true

[functions.public-stats]
verify_jwt = false
