project_id = "hnkyeohwjcqhgulgdydd"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.signup-with-pin]
verify_jwt = false

[functions.login-with-pin]
verify_jwt = false

[functions.create-employee-user]
verify_jwt = true

[functions.submit-wishlist]
verify_jwt = false

[functions.wishlist-shop-info]
verify_jwt = false

[functions.bootstrap-admin]
verify_jwt = false