/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AffiliateRouteImport } from './routes/affiliate'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as UsernameRouteImport } from './routes/$username'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as FSlugRouteImport } from './routes/f.$slug'
import { Route as AppWarrantyRouteImport } from './routes/app.warranty'
import { Route as AppTrainingRouteImport } from './routes/app.training'
import { Route as AppSubscribeRouteImport } from './routes/app.subscribe'
import { Route as AppStockEditRouteImport } from './routes/app.stock-edit'
import { Route as AppStockRouteImport } from './routes/app.stock'
import { Route as AppShopsRouteImport } from './routes/app.shops'
import { Route as AppSellRouteImport } from './routes/app.sell'
import { Route as AppSalesLedgerRouteImport } from './routes/app.sales-ledger'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppRecycleBinRouteImport } from './routes/app.recycle-bin'
import { Route as AppQuickOrderRouteImport } from './routes/app.quick-order'
import { Route as AppPurchaseLedgerRouteImport } from './routes/app.purchase-ledger'
import { Route as AppPurchaseRouteImport } from './routes/app.purchase'
import { Route as AppProductsRouteImport } from './routes/app.products'
import { Route as AppPrinterRouteImport } from './routes/app.printer'
import { Route as AppOnlineShopRouteImport } from './routes/app.online-shop'
import { Route as AppMarketingRouteImport } from './routes/app.marketing'
import { Route as AppExpiringRouteImport } from './routes/app.expiring'
import { Route as AppExpenseLedgerRouteImport } from './routes/app.expense-ledger'
import { Route as AppDueLedgerRouteImport } from './routes/app.due-ledger'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCustomerWishlistRouteImport } from './routes/app.customer-wishlist'
import { Route as AppContactsRouteImport } from './routes/app.contacts'
import { Route as AppCombinedReportRouteImport } from './routes/app.combined-report'
import { Route as AppCashboxRouteImport } from './routes/app.cashbox'
import { Route as AppAffiliateRouteImport } from './routes/app.affiliate'
import { Route as AppAccessRouteImport } from './routes/app.access'
import { Route as AffiliateRegisterRouteImport } from './routes/affiliate.register'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTrainingRouteImport } from './routes/admin.training'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminSubscriptionRequestsRouteImport } from './routes/admin.subscription-requests'
import { Route as AdminShopTypesRouteImport } from './routes/admin.shop-types'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminMarketplaceRouteImport } from './routes/admin.marketplace'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLandingRouteImport } from './routes/admin.landing'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminAffiliatesRouteImport } from './routes/admin.affiliates'
import { Route as ShopSSlugRouteImport } from './routes/shop.s.$slug'
import { Route as ShopPIdRouteImport } from './routes/shop.p.$id'
import { Route as FSlugMyRouteImport } from './routes/f.$slug.my'
import { Route as AppOnlineShopThemesRouteImport } from './routes/app.online-shop.themes'
import { Route as AppOnlineShopSettingsRouteImport } from './routes/app.online-shop.settings'
import { Route as AppOnlineShopProductsRouteImport } from './routes/app.online-shop.products'
import { Route as AppOnlineShopOrdersRouteImport } from './routes/app.online-shop.orders'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateRoute = AffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRoute = UsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const FSlugRoute = FSlugRouteImport.update({
  id: '/f/$slug',
  path: '/f/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWarrantyRoute = AppWarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => AppRoute,
} as any)
const AppTrainingRoute = AppTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscribeRoute = AppSubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => AppRoute,
} as any)
const AppStockEditRoute = AppStockEditRouteImport.update({
  id: '/stock-edit',
  path: '/stock-edit',
  getParentRoute: () => AppRoute,
} as any)
const AppStockRoute = AppStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AppRoute,
} as any)
const AppShopsRoute = AppShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => AppRoute,
} as any)
const AppSellRoute = AppSellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesLedgerRoute = AppSalesLedgerRouteImport.update({
  id: '/sales-ledger',
  path: '/sales-ledger',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRecycleBinRoute = AppRecycleBinRouteImport.update({
  id: '/recycle-bin',
  path: '/recycle-bin',
  getParentRoute: () => AppRoute,
} as any)
const AppQuickOrderRoute = AppQuickOrderRouteImport.update({
  id: '/quick-order',
  path: '/quick-order',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseLedgerRoute = AppPurchaseLedgerRouteImport.update({
  id: '/purchase-ledger',
  path: '/purchase-ledger',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseRoute = AppPurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppPrinterRoute = AppPrinterRouteImport.update({
  id: '/printer',
  path: '/printer',
  getParentRoute: () => AppRoute,
} as any)
const AppOnlineShopRoute = AppOnlineShopRouteImport.update({
  id: '/online-shop',
  path: '/online-shop',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingRoute = AppMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AppRoute,
} as any)
const AppExpiringRoute = AppExpiringRouteImport.update({
  id: '/expiring',
  path: '/expiring',
  getParentRoute: () => AppRoute,
} as any)
const AppExpenseLedgerRoute = AppExpenseLedgerRouteImport.update({
  id: '/expense-ledger',
  path: '/expense-ledger',
  getParentRoute: () => AppRoute,
} as any)
const AppDueLedgerRoute = AppDueLedgerRouteImport.update({
  id: '/due-ledger',
  path: '/due-ledger',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomerWishlistRoute = AppCustomerWishlistRouteImport.update({
  id: '/customer-wishlist',
  path: '/customer-wishlist',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppCombinedReportRoute = AppCombinedReportRouteImport.update({
  id: '/combined-report',
  path: '/combined-report',
  getParentRoute: () => AppRoute,
} as any)
const AppCashboxRoute = AppCashboxRouteImport.update({
  id: '/cashbox',
  path: '/cashbox',
  getParentRoute: () => AppRoute,
} as any)
const AppAffiliateRoute = AppAffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => AppRoute,
} as any)
const AppAccessRoute = AppAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AppRoute,
} as any)
const AffiliateRegisterRoute = AffiliateRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AffiliateRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrainingRoute = AdminTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionRequestsRoute =
  AdminSubscriptionRequestsRouteImport.update({
    id: '/subscription-requests',
    path: '/subscription-requests',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminShopTypesRoute = AdminShopTypesRouteImport.update({
  id: '/shop-types',
  path: '/shop-types',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketplaceRoute = AdminMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLandingRoute = AdminLandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAffiliatesRoute = AdminAffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => AdminRoute,
} as any)
const ShopSSlugRoute = ShopSSlugRouteImport.update({
  id: '/shop/s/$slug',
  path: '/shop/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopPIdRoute = ShopPIdRouteImport.update({
  id: '/shop/p/$id',
  path: '/shop/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FSlugMyRoute = FSlugMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => FSlugRoute,
} as any)
const AppOnlineShopThemesRoute = AppOnlineShopThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => AppOnlineShopRoute,
} as any)
const AppOnlineShopSettingsRoute = AppOnlineShopSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppOnlineShopRoute,
} as any)
const AppOnlineShopProductsRoute = AppOnlineShopProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppOnlineShopRoute,
} as any)
const AppOnlineShopOrdersRoute = AppOnlineShopOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppOnlineShopRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/admin': typeof AdminRouteWithChildren
  '/affiliate': typeof AffiliateRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/landing': typeof AdminLandingRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/marketplace': typeof AdminMarketplaceRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shop-types': typeof AdminShopTypesRoute
  '/admin/subscription-requests': typeof AdminSubscriptionRequestsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/training': typeof AdminTrainingRoute
  '/admin/users': typeof AdminUsersRoute
  '/affiliate/register': typeof AffiliateRegisterRoute
  '/app/access': typeof AppAccessRoute
  '/app/affiliate': typeof AppAffiliateRoute
  '/app/cashbox': typeof AppCashboxRoute
  '/app/combined-report': typeof AppCombinedReportRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/customer-wishlist': typeof AppCustomerWishlistRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/due-ledger': typeof AppDueLedgerRoute
  '/app/expense-ledger': typeof AppExpenseLedgerRoute
  '/app/expiring': typeof AppExpiringRoute
  '/app/marketing': typeof AppMarketingRoute
  '/app/online-shop': typeof AppOnlineShopRouteWithChildren
  '/app/printer': typeof AppPrinterRoute
  '/app/products': typeof AppProductsRoute
  '/app/purchase': typeof AppPurchaseRoute
  '/app/purchase-ledger': typeof AppPurchaseLedgerRoute
  '/app/quick-order': typeof AppQuickOrderRoute
  '/app/recycle-bin': typeof AppRecycleBinRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sales-ledger': typeof AppSalesLedgerRoute
  '/app/sell': typeof AppSellRoute
  '/app/shops': typeof AppShopsRoute
  '/app/stock': typeof AppStockRoute
  '/app/stock-edit': typeof AppStockEditRoute
  '/app/subscribe': typeof AppSubscribeRoute
  '/app/training': typeof AppTrainingRoute
  '/app/warranty': typeof AppWarrantyRoute
  '/f/$slug': typeof FSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/app/online-shop/orders': typeof AppOnlineShopOrdersRoute
  '/app/online-shop/products': typeof AppOnlineShopProductsRoute
  '/app/online-shop/settings': typeof AppOnlineShopSettingsRoute
  '/app/online-shop/themes': typeof AppOnlineShopThemesRoute
  '/f/$slug/my': typeof FSlugMyRoute
  '/shop/p/$id': typeof ShopPIdRoute
  '/shop/s/$slug': typeof ShopSSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/affiliate': typeof AffiliateRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/landing': typeof AdminLandingRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/marketplace': typeof AdminMarketplaceRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shop-types': typeof AdminShopTypesRoute
  '/admin/subscription-requests': typeof AdminSubscriptionRequestsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/training': typeof AdminTrainingRoute
  '/admin/users': typeof AdminUsersRoute
  '/affiliate/register': typeof AffiliateRegisterRoute
  '/app/access': typeof AppAccessRoute
  '/app/affiliate': typeof AppAffiliateRoute
  '/app/cashbox': typeof AppCashboxRoute
  '/app/combined-report': typeof AppCombinedReportRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/customer-wishlist': typeof AppCustomerWishlistRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/due-ledger': typeof AppDueLedgerRoute
  '/app/expense-ledger': typeof AppExpenseLedgerRoute
  '/app/expiring': typeof AppExpiringRoute
  '/app/marketing': typeof AppMarketingRoute
  '/app/online-shop': typeof AppOnlineShopRouteWithChildren
  '/app/printer': typeof AppPrinterRoute
  '/app/products': typeof AppProductsRoute
  '/app/purchase': typeof AppPurchaseRoute
  '/app/purchase-ledger': typeof AppPurchaseLedgerRoute
  '/app/quick-order': typeof AppQuickOrderRoute
  '/app/recycle-bin': typeof AppRecycleBinRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sales-ledger': typeof AppSalesLedgerRoute
  '/app/sell': typeof AppSellRoute
  '/app/shops': typeof AppShopsRoute
  '/app/stock': typeof AppStockRoute
  '/app/stock-edit': typeof AppStockEditRoute
  '/app/subscribe': typeof AppSubscribeRoute
  '/app/training': typeof AppTrainingRoute
  '/app/warranty': typeof AppWarrantyRoute
  '/f/$slug': typeof FSlugRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/shop': typeof ShopIndexRoute
  '/app/online-shop/orders': typeof AppOnlineShopOrdersRoute
  '/app/online-shop/products': typeof AppOnlineShopProductsRoute
  '/app/online-shop/settings': typeof AppOnlineShopSettingsRoute
  '/app/online-shop/themes': typeof AppOnlineShopThemesRoute
  '/f/$slug/my': typeof FSlugMyRoute
  '/shop/p/$id': typeof ShopPIdRoute
  '/shop/s/$slug': typeof ShopSSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/admin': typeof AdminRouteWithChildren
  '/affiliate': typeof AffiliateRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/landing': typeof AdminLandingRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/marketplace': typeof AdminMarketplaceRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shop-types': typeof AdminShopTypesRoute
  '/admin/subscription-requests': typeof AdminSubscriptionRequestsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/training': typeof AdminTrainingRoute
  '/admin/users': typeof AdminUsersRoute
  '/affiliate/register': typeof AffiliateRegisterRoute
  '/app/access': typeof AppAccessRoute
  '/app/affiliate': typeof AppAffiliateRoute
  '/app/cashbox': typeof AppCashboxRoute
  '/app/combined-report': typeof AppCombinedReportRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/customer-wishlist': typeof AppCustomerWishlistRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/due-ledger': typeof AppDueLedgerRoute
  '/app/expense-ledger': typeof AppExpenseLedgerRoute
  '/app/expiring': typeof AppExpiringRoute
  '/app/marketing': typeof AppMarketingRoute
  '/app/online-shop': typeof AppOnlineShopRouteWithChildren
  '/app/printer': typeof AppPrinterRoute
  '/app/products': typeof AppProductsRoute
  '/app/purchase': typeof AppPurchaseRoute
  '/app/purchase-ledger': typeof AppPurchaseLedgerRoute
  '/app/quick-order': typeof AppQuickOrderRoute
  '/app/recycle-bin': typeof AppRecycleBinRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sales-ledger': typeof AppSalesLedgerRoute
  '/app/sell': typeof AppSellRoute
  '/app/shops': typeof AppShopsRoute
  '/app/stock': typeof AppStockRoute
  '/app/stock-edit': typeof AppStockEditRoute
  '/app/subscribe': typeof AppSubscribeRoute
  '/app/training': typeof AppTrainingRoute
  '/app/warranty': typeof AppWarrantyRoute
  '/f/$slug': typeof FSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/app/online-shop/orders': typeof AppOnlineShopOrdersRoute
  '/app/online-shop/products': typeof AppOnlineShopProductsRoute
  '/app/online-shop/settings': typeof AppOnlineShopSettingsRoute
  '/app/online-shop/themes': typeof AppOnlineShopThemesRoute
  '/f/$slug/my': typeof FSlugMyRoute
  '/shop/p/$id': typeof ShopPIdRoute
  '/shop/s/$slug': typeof ShopSSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$username'
    | '/admin'
    | '/affiliate'
    | '/app'
    | '/auth'
    | '/pricing'
    | '/admin/affiliates'
    | '/admin/banners'
    | '/admin/landing'
    | '/admin/login'
    | '/admin/marketplace'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/shop-types'
    | '/admin/subscription-requests'
    | '/admin/subscriptions'
    | '/admin/training'
    | '/admin/users'
    | '/affiliate/register'
    | '/app/access'
    | '/app/affiliate'
    | '/app/cashbox'
    | '/app/combined-report'
    | '/app/contacts'
    | '/app/customer-wishlist'
    | '/app/dashboard'
    | '/app/due-ledger'
    | '/app/expense-ledger'
    | '/app/expiring'
    | '/app/marketing'
    | '/app/online-shop'
    | '/app/printer'
    | '/app/products'
    | '/app/purchase'
    | '/app/purchase-ledger'
    | '/app/quick-order'
    | '/app/recycle-bin'
    | '/app/reports'
    | '/app/sales-ledger'
    | '/app/sell'
    | '/app/shops'
    | '/app/stock'
    | '/app/stock-edit'
    | '/app/subscribe'
    | '/app/training'
    | '/app/warranty'
    | '/f/$slug'
    | '/admin/'
    | '/shop/'
    | '/app/online-shop/orders'
    | '/app/online-shop/products'
    | '/app/online-shop/settings'
    | '/app/online-shop/themes'
    | '/f/$slug/my'
    | '/shop/p/$id'
    | '/shop/s/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$username'
    | '/affiliate'
    | '/app'
    | '/auth'
    | '/pricing'
    | '/admin/affiliates'
    | '/admin/banners'
    | '/admin/landing'
    | '/admin/login'
    | '/admin/marketplace'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/shop-types'
    | '/admin/subscription-requests'
    | '/admin/subscriptions'
    | '/admin/training'
    | '/admin/users'
    | '/affiliate/register'
    | '/app/access'
    | '/app/affiliate'
    | '/app/cashbox'
    | '/app/combined-report'
    | '/app/contacts'
    | '/app/customer-wishlist'
    | '/app/dashboard'
    | '/app/due-ledger'
    | '/app/expense-ledger'
    | '/app/expiring'
    | '/app/marketing'
    | '/app/online-shop'
    | '/app/printer'
    | '/app/products'
    | '/app/purchase'
    | '/app/purchase-ledger'
    | '/app/quick-order'
    | '/app/recycle-bin'
    | '/app/reports'
    | '/app/sales-ledger'
    | '/app/sell'
    | '/app/shops'
    | '/app/stock'
    | '/app/stock-edit'
    | '/app/subscribe'
    | '/app/training'
    | '/app/warranty'
    | '/f/$slug'
    | '/admin'
    | '/shop'
    | '/app/online-shop/orders'
    | '/app/online-shop/products'
    | '/app/online-shop/settings'
    | '/app/online-shop/themes'
    | '/f/$slug/my'
    | '/shop/p/$id'
    | '/shop/s/$slug'
  id:
    | '__root__'
    | '/'
    | '/$username'
    | '/admin'
    | '/affiliate'
    | '/app'
    | '/auth'
    | '/pricing'
    | '/admin/affiliates'
    | '/admin/banners'
    | '/admin/landing'
    | '/admin/login'
    | '/admin/marketplace'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/shop-types'
    | '/admin/subscription-requests'
    | '/admin/subscriptions'
    | '/admin/training'
    | '/admin/users'
    | '/affiliate/register'
    | '/app/access'
    | '/app/affiliate'
    | '/app/cashbox'
    | '/app/combined-report'
    | '/app/contacts'
    | '/app/customer-wishlist'
    | '/app/dashboard'
    | '/app/due-ledger'
    | '/app/expense-ledger'
    | '/app/expiring'
    | '/app/marketing'
    | '/app/online-shop'
    | '/app/printer'
    | '/app/products'
    | '/app/purchase'
    | '/app/purchase-ledger'
    | '/app/quick-order'
    | '/app/recycle-bin'
    | '/app/reports'
    | '/app/sales-ledger'
    | '/app/sell'
    | '/app/shops'
    | '/app/stock'
    | '/app/stock-edit'
    | '/app/subscribe'
    | '/app/training'
    | '/app/warranty'
    | '/f/$slug'
    | '/admin/'
    | '/shop/'
    | '/app/online-shop/orders'
    | '/app/online-shop/products'
    | '/app/online-shop/settings'
    | '/app/online-shop/themes'
    | '/f/$slug/my'
    | '/shop/p/$id'
    | '/shop/s/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsernameRoute: typeof UsernameRoute
  AdminRoute: typeof AdminRouteWithChildren
  AffiliateRoute: typeof AffiliateRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  PricingRoute: typeof PricingRoute
  FSlugRoute: typeof FSlugRouteWithChildren
  ShopIndexRoute: typeof ShopIndexRoute
  ShopPIdRoute: typeof ShopPIdRoute
  ShopSSlugRoute: typeof ShopSSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate': {
      id: '/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/f/$slug': {
      id: '/f/$slug'
      path: '/f/$slug'
      fullPath: '/f/$slug'
      preLoaderRoute: typeof FSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/warranty': {
      id: '/app/warranty'
      path: '/warranty'
      fullPath: '/app/warranty'
      preLoaderRoute: typeof AppWarrantyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/training': {
      id: '/app/training'
      path: '/training'
      fullPath: '/app/training'
      preLoaderRoute: typeof AppTrainingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subscribe': {
      id: '/app/subscribe'
      path: '/subscribe'
      fullPath: '/app/subscribe'
      preLoaderRoute: typeof AppSubscribeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stock-edit': {
      id: '/app/stock-edit'
      path: '/stock-edit'
      fullPath: '/app/stock-edit'
      preLoaderRoute: typeof AppStockEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stock': {
      id: '/app/stock'
      path: '/stock'
      fullPath: '/app/stock'
      preLoaderRoute: typeof AppStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/shops': {
      id: '/app/shops'
      path: '/shops'
      fullPath: '/app/shops'
      preLoaderRoute: typeof AppShopsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sell': {
      id: '/app/sell'
      path: '/sell'
      fullPath: '/app/sell'
      preLoaderRoute: typeof AppSellRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sales-ledger': {
      id: '/app/sales-ledger'
      path: '/sales-ledger'
      fullPath: '/app/sales-ledger'
      preLoaderRoute: typeof AppSalesLedgerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recycle-bin': {
      id: '/app/recycle-bin'
      path: '/recycle-bin'
      fullPath: '/app/recycle-bin'
      preLoaderRoute: typeof AppRecycleBinRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quick-order': {
      id: '/app/quick-order'
      path: '/quick-order'
      fullPath: '/app/quick-order'
      preLoaderRoute: typeof AppQuickOrderRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/purchase-ledger': {
      id: '/app/purchase-ledger'
      path: '/purchase-ledger'
      fullPath: '/app/purchase-ledger'
      preLoaderRoute: typeof AppPurchaseLedgerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/purchase': {
      id: '/app/purchase'
      path: '/purchase'
      fullPath: '/app/purchase'
      preLoaderRoute: typeof AppPurchaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products': {
      id: '/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/printer': {
      id: '/app/printer'
      path: '/printer'
      fullPath: '/app/printer'
      preLoaderRoute: typeof AppPrinterRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/online-shop': {
      id: '/app/online-shop'
      path: '/online-shop'
      fullPath: '/app/online-shop'
      preLoaderRoute: typeof AppOnlineShopRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marketing': {
      id: '/app/marketing'
      path: '/marketing'
      fullPath: '/app/marketing'
      preLoaderRoute: typeof AppMarketingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/expiring': {
      id: '/app/expiring'
      path: '/expiring'
      fullPath: '/app/expiring'
      preLoaderRoute: typeof AppExpiringRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/expense-ledger': {
      id: '/app/expense-ledger'
      path: '/expense-ledger'
      fullPath: '/app/expense-ledger'
      preLoaderRoute: typeof AppExpenseLedgerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/due-ledger': {
      id: '/app/due-ledger'
      path: '/due-ledger'
      fullPath: '/app/due-ledger'
      preLoaderRoute: typeof AppDueLedgerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customer-wishlist': {
      id: '/app/customer-wishlist'
      path: '/customer-wishlist'
      fullPath: '/app/customer-wishlist'
      preLoaderRoute: typeof AppCustomerWishlistRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contacts': {
      id: '/app/contacts'
      path: '/contacts'
      fullPath: '/app/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/combined-report': {
      id: '/app/combined-report'
      path: '/combined-report'
      fullPath: '/app/combined-report'
      preLoaderRoute: typeof AppCombinedReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cashbox': {
      id: '/app/cashbox'
      path: '/cashbox'
      fullPath: '/app/cashbox'
      preLoaderRoute: typeof AppCashboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/affiliate': {
      id: '/app/affiliate'
      path: '/affiliate'
      fullPath: '/app/affiliate'
      preLoaderRoute: typeof AppAffiliateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/access': {
      id: '/app/access'
      path: '/access'
      fullPath: '/app/access'
      preLoaderRoute: typeof AppAccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/affiliate/register': {
      id: '/affiliate/register'
      path: '/register'
      fullPath: '/affiliate/register'
      preLoaderRoute: typeof AffiliateRegisterRouteImport
      parentRoute: typeof AffiliateRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/training': {
      id: '/admin/training'
      path: '/training'
      fullPath: '/admin/training'
      preLoaderRoute: typeof AdminTrainingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscription-requests': {
      id: '/admin/subscription-requests'
      path: '/subscription-requests'
      fullPath: '/admin/subscription-requests'
      preLoaderRoute: typeof AdminSubscriptionRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shop-types': {
      id: '/admin/shop-types'
      path: '/shop-types'
      fullPath: '/admin/shop-types'
      preLoaderRoute: typeof AdminShopTypesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketplace': {
      id: '/admin/marketplace'
      path: '/marketplace'
      fullPath: '/admin/marketplace'
      preLoaderRoute: typeof AdminMarketplaceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/landing': {
      id: '/admin/landing'
      path: '/landing'
      fullPath: '/admin/landing'
      preLoaderRoute: typeof AdminLandingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/affiliates': {
      id: '/admin/affiliates'
      path: '/affiliates'
      fullPath: '/admin/affiliates'
      preLoaderRoute: typeof AdminAffiliatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/shop/s/$slug': {
      id: '/shop/s/$slug'
      path: '/shop/s/$slug'
      fullPath: '/shop/s/$slug'
      preLoaderRoute: typeof ShopSSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/p/$id': {
      id: '/shop/p/$id'
      path: '/shop/p/$id'
      fullPath: '/shop/p/$id'
      preLoaderRoute: typeof ShopPIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$slug/my': {
      id: '/f/$slug/my'
      path: '/my'
      fullPath: '/f/$slug/my'
      preLoaderRoute: typeof FSlugMyRouteImport
      parentRoute: typeof FSlugRoute
    }
    '/app/online-shop/themes': {
      id: '/app/online-shop/themes'
      path: '/themes'
      fullPath: '/app/online-shop/themes'
      preLoaderRoute: typeof AppOnlineShopThemesRouteImport
      parentRoute: typeof AppOnlineShopRoute
    }
    '/app/online-shop/settings': {
      id: '/app/online-shop/settings'
      path: '/settings'
      fullPath: '/app/online-shop/settings'
      preLoaderRoute: typeof AppOnlineShopSettingsRouteImport
      parentRoute: typeof AppOnlineShopRoute
    }
    '/app/online-shop/products': {
      id: '/app/online-shop/products'
      path: '/products'
      fullPath: '/app/online-shop/products'
      preLoaderRoute: typeof AppOnlineShopProductsRouteImport
      parentRoute: typeof AppOnlineShopRoute
    }
    '/app/online-shop/orders': {
      id: '/app/online-shop/orders'
      path: '/orders'
      fullPath: '/app/online-shop/orders'
      preLoaderRoute: typeof AppOnlineShopOrdersRouteImport
      parentRoute: typeof AppOnlineShopRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAffiliatesRoute: typeof AdminAffiliatesRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminLandingRoute: typeof AdminLandingRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMarketplaceRoute: typeof AdminMarketplaceRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminShopTypesRoute: typeof AdminShopTypesRoute
  AdminSubscriptionRequestsRoute: typeof AdminSubscriptionRequestsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminTrainingRoute: typeof AdminTrainingRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAffiliatesRoute: AdminAffiliatesRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminLandingRoute: AdminLandingRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMarketplaceRoute: AdminMarketplaceRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminShopTypesRoute: AdminShopTypesRoute,
  AdminSubscriptionRequestsRoute: AdminSubscriptionRequestsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminTrainingRoute: AdminTrainingRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AffiliateRouteChildren {
  AffiliateRegisterRoute: typeof AffiliateRegisterRoute
}

const AffiliateRouteChildren: AffiliateRouteChildren = {
  AffiliateRegisterRoute: AffiliateRegisterRoute,
}

const AffiliateRouteWithChildren = AffiliateRoute._addFileChildren(
  AffiliateRouteChildren,
)

interface AppOnlineShopRouteChildren {
  AppOnlineShopOrdersRoute: typeof AppOnlineShopOrdersRoute
  AppOnlineShopProductsRoute: typeof AppOnlineShopProductsRoute
  AppOnlineShopSettingsRoute: typeof AppOnlineShopSettingsRoute
  AppOnlineShopThemesRoute: typeof AppOnlineShopThemesRoute
}

const AppOnlineShopRouteChildren: AppOnlineShopRouteChildren = {
  AppOnlineShopOrdersRoute: AppOnlineShopOrdersRoute,
  AppOnlineShopProductsRoute: AppOnlineShopProductsRoute,
  AppOnlineShopSettingsRoute: AppOnlineShopSettingsRoute,
  AppOnlineShopThemesRoute: AppOnlineShopThemesRoute,
}

const AppOnlineShopRouteWithChildren = AppOnlineShopRoute._addFileChildren(
  AppOnlineShopRouteChildren,
)

interface AppRouteChildren {
  AppAccessRoute: typeof AppAccessRoute
  AppAffiliateRoute: typeof AppAffiliateRoute
  AppCashboxRoute: typeof AppCashboxRoute
  AppCombinedReportRoute: typeof AppCombinedReportRoute
  AppContactsRoute: typeof AppContactsRoute
  AppCustomerWishlistRoute: typeof AppCustomerWishlistRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDueLedgerRoute: typeof AppDueLedgerRoute
  AppExpenseLedgerRoute: typeof AppExpenseLedgerRoute
  AppExpiringRoute: typeof AppExpiringRoute
  AppMarketingRoute: typeof AppMarketingRoute
  AppOnlineShopRoute: typeof AppOnlineShopRouteWithChildren
  AppPrinterRoute: typeof AppPrinterRoute
  AppProductsRoute: typeof AppProductsRoute
  AppPurchaseRoute: typeof AppPurchaseRoute
  AppPurchaseLedgerRoute: typeof AppPurchaseLedgerRoute
  AppQuickOrderRoute: typeof AppQuickOrderRoute
  AppRecycleBinRoute: typeof AppRecycleBinRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSalesLedgerRoute: typeof AppSalesLedgerRoute
  AppSellRoute: typeof AppSellRoute
  AppShopsRoute: typeof AppShopsRoute
  AppStockRoute: typeof AppStockRoute
  AppStockEditRoute: typeof AppStockEditRoute
  AppSubscribeRoute: typeof AppSubscribeRoute
  AppTrainingRoute: typeof AppTrainingRoute
  AppWarrantyRoute: typeof AppWarrantyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccessRoute: AppAccessRoute,
  AppAffiliateRoute: AppAffiliateRoute,
  AppCashboxRoute: AppCashboxRoute,
  AppCombinedReportRoute: AppCombinedReportRoute,
  AppContactsRoute: AppContactsRoute,
  AppCustomerWishlistRoute: AppCustomerWishlistRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDueLedgerRoute: AppDueLedgerRoute,
  AppExpenseLedgerRoute: AppExpenseLedgerRoute,
  AppExpiringRoute: AppExpiringRoute,
  AppMarketingRoute: AppMarketingRoute,
  AppOnlineShopRoute: AppOnlineShopRouteWithChildren,
  AppPrinterRoute: AppPrinterRoute,
  AppProductsRoute: AppProductsRoute,
  AppPurchaseRoute: AppPurchaseRoute,
  AppPurchaseLedgerRoute: AppPurchaseLedgerRoute,
  AppQuickOrderRoute: AppQuickOrderRoute,
  AppRecycleBinRoute: AppRecycleBinRoute,
  AppReportsRoute: AppReportsRoute,
  AppSalesLedgerRoute: AppSalesLedgerRoute,
  AppSellRoute: AppSellRoute,
  AppShopsRoute: AppShopsRoute,
  AppStockRoute: AppStockRoute,
  AppStockEditRoute: AppStockEditRoute,
  AppSubscribeRoute: AppSubscribeRoute,
  AppTrainingRoute: AppTrainingRoute,
  AppWarrantyRoute: AppWarrantyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface FSlugRouteChildren {
  FSlugMyRoute: typeof FSlugMyRoute
}

const FSlugRouteChildren: FSlugRouteChildren = {
  FSlugMyRoute: FSlugMyRoute,
}

const FSlugRouteWithChildren = FSlugRoute._addFileChildren(FSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsernameRoute: UsernameRoute,
  AdminRoute: AdminRouteWithChildren,
  AffiliateRoute: AffiliateRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  PricingRoute: PricingRoute,
  FSlugRoute: FSlugRouteWithChildren,
  ShopIndexRoute: ShopIndexRoute,
  ShopPIdRoute: ShopPIdRoute,
  ShopSSlugRoute: ShopSSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
