-- Add metropolitan thanas to bd_upazilas (treating thana == upazila as user confirmed)
-- Uses legacy_id prefixed with 'metro_' to avoid collision with bdapi numeric IDs

INSERT INTO public.bd_upazilas (legacy_id, district_legacy_id, name_bn, name_en, is_active) VALUES
-- Dhaka Metropolitan (district 47) — 50 thanas
('metro_dha_01','47','রমনা','Ramna',true),
('metro_dha_02','47','ধানমন্ডি','Dhanmondi',true),
('metro_dha_03','47','নিউমার্কেট','New Market',true),
('metro_dha_04','47','লালবাগ','Lalbagh',true),
('metro_dha_05','47','চকবাজার','Chawkbazar',true),
('metro_dha_06','47','কোতোয়ালি','Kotwali',true),
('metro_dha_07','47','সূত্রাপুর','Sutrapur',true),
('metro_dha_08','47','গেন্ডারিয়া','Gendaria',true),
('metro_dha_09','47','ওয়ারী','Wari',true),
('metro_dha_10','47','শ্যামপুর','Shyampur',true),
('metro_dha_11','47','কদমতলী','Kadamtali',true),
('metro_dha_12','47','ডেমরা','Demra',true),
('metro_dha_13','47','যাত্রাবাড়ী','Jatrabari',true),
('metro_dha_14','47','শাহজাহানপুর','Shahjahanpur',true),
('metro_dha_15','47','মুগদা','Mugda',true),
('metro_dha_16','47','সবুজবাগ','Sabujbagh',true),
('metro_dha_17','47','খিলগাঁও','Khilgaon',true),
('metro_dha_18','47','মতিঝিল','Motijheel',true),
('metro_dha_19','47','পল্টন','Paltan',true),
('metro_dha_20','47','শাহবাগ','Shahbagh',true),
('metro_dha_21','47','তেজগাঁও','Tejgaon',true),
('metro_dha_22','47','তেজগাঁও শিল্প এলাকা','Tejgaon Industrial Area',true),
('metro_dha_23','47','হাতিরঝিল','Hatirjheel',true),
('metro_dha_24','47','রামপুরা','Rampura',true),
('metro_dha_25','47','বাড্ডা','Badda',true),
('metro_dha_26','47','ভাটারা','Bhatara',true),
('metro_dha_27','47','গুলশান','Gulshan',true),
('metro_dha_28','47','বনানী','Banani',true),
('metro_dha_29','47','ক্যান্টনমেন্ট','Cantonment',true),
('metro_dha_30','47','কাফরুল','Kafrul',true),
('metro_dha_31','47','ভাষানটেক','Bhasantek',true),
('metro_dha_32','47','মিরপুর','Mirpur',true),
('metro_dha_33','47','পল্লবী','Pallabi',true),
('metro_dha_34','47','রূপনগর','Rupnagar',true),
('metro_dha_35','47','শাহ আলী','Shah Ali',true),
('metro_dha_36','47','দারুসসালাম','Darus Salam',true),
('metro_dha_37','47','উত্তরা পশ্চিম','Uttara West',true),
('metro_dha_38','47','উত্তরা পূর্ব','Uttara East',true),
('metro_dha_39','47','দক্ষিণখান','Dakshinkhan',true),
('metro_dha_40','47','উত্তরখান','Uttarkhan',true),
('metro_dha_41','47','তুরাগ','Turag',true),
('metro_dha_42','47','বিমানবন্দর','Airport',true),
('metro_dha_43','47','খিলক্ষেত','Khilkhet',true),
('metro_dha_44','47','মোহাম্মদপুর','Mohammadpur',true),
('metro_dha_45','47','আদাবর','Adabor',true),
('metro_dha_46','47','হাজারীবাগ','Hazaribagh',true),
('metro_dha_47','47','কামরাঙ্গীরচর','Kamrangirchar',true),
('metro_dha_48','47','গুলিস্তান','Gulistan',true),
('metro_dha_49','47','বংশাল','Bangshal',true),
('metro_dha_50','47','দক্ষিণ কেরাণীগঞ্জ','South Keraniganj',true),

-- Chattogram Metropolitan (district 8) — 16 thanas
('metro_ctg_01','8','কোতোয়ালি','Kotwali',true),
('metro_ctg_02','8','পাঁচলাইশ','Panchlaish',true),
('metro_ctg_03','8','ডবলমুরিং','Double Mooring',true),
('metro_ctg_04','8','চান্দগাঁও','Chandgaon',true),
('metro_ctg_05','8','বায়েজিদ বোস্তামী','Bayazid Bostami',true),
('metro_ctg_06','8','বন্দর','Bandar',true),
('metro_ctg_07','8','পতেঙ্গা','Patenga',true),
('metro_ctg_08','8','হালিশহর','Halishahar',true),
('metro_ctg_09','8','খুলশী','Khulshi',true),
('metro_ctg_10','8','পাহাড়তলী','Pahartali',true),
('metro_ctg_11','8','আকবরশাহ','Akbar Shah',true),
('metro_ctg_12','8','সদরঘাট','Sadarghat',true),
('metro_ctg_13','8','বাকলিয়া','Bakalia',true),
('metro_ctg_14','8','ইপিজেড','EPZ',true),
('metro_ctg_15','8','কর্ণফুলী','Karnaphuli',true),
('metro_ctg_16','8','চকবাজার','Chawkbazar',true),

-- Khulna Metropolitan (district 27) — 8 thanas
('metro_khu_01','27','খুলনা সদর','Khulna Sadar',true),
('metro_khu_02','27','সোনাডাঙ্গা','Sonadanga',true),
('metro_khu_03','27','খালিশপুর','Khalishpur',true),
('metro_khu_04','27','দৌলতপুর','Daulatpur',true),
('metro_khu_05','27','খানজাহান আলী','Khan Jahan Ali',true),
('metro_khu_06','27','লবণচরা','Labanchara',true),
('metro_khu_07','27','হরিণটানা','Harintana',true),
('metro_khu_08','27','আড়ংঘাটা','Aronghata',true),

-- Rajshahi Metropolitan (district 15) — 5 thanas
('metro_raj_01','15','বোয়ালিয়া','Boalia',true),
('metro_raj_02','15','রাজপাড়া','Rajpara',true),
('metro_raj_03','15','মতিহার','Motihar',true),
('metro_raj_04','15','শাহ মখদুম','Shah Makhdum',true),
('metro_raj_05','15','চন্দ্রিমা','Chandrima',true),

-- Sylhet Metropolitan (district 36) — 6 thanas
('metro_syl_01','36','কোতোয়ালি','Kotwali',true),
('metro_syl_02','36','জালালাবাদ','Jalalabad',true),
('metro_syl_03','36','এয়ারপোর্ট','Airport',true),
('metro_syl_04','36','দক্ষিণ সুরমা','South Surma',true),
('metro_syl_05','36','শাহপরান','Shahporan',true),
('metro_syl_06','36','মোগলাবাজার','Moglabazar',true),

-- Barishal Metropolitan (district 33) — 4 thanas
('metro_bar_01','33','কোতোয়ালি','Kotwali',true),
('metro_bar_02','33','বিমানবন্দর','Airport',true),
('metro_bar_03','33','কাউনিয়া','Kawnia',true),
('metro_bar_04','33','বন্দর','Bandar',true),

-- Rangpur Metropolitan (district 59) — 6 thanas
('metro_ran_01','59','কোতোয়ালি','Kotwali',true),
('metro_ran_02','59','মাহিগঞ্জ','Mahiganj',true),
('metro_ran_03','59','হারাগাছ','Haragach',true),
('metro_ran_04','59','হাজীরহাট','Hajirhat',true),
('metro_ran_05','59','পরশুরাম','Parshuram',true),
('metro_ran_06','59','তাজহাট','Tajhat',true),

-- Mymensingh Metropolitan (district 62) — 4 thanas
('metro_mym_01','62','কোতোয়ালি','Kotwali',true),
('metro_mym_02','62','সদর','Sadar',true),
('metro_mym_03','62','পাটগুদাম','Patgudam',true),
('metro_mym_04','62','গৌরীপুর','Gauripur Metro',true),

-- Gazipur Metropolitan (district 41) — 8 thanas
('metro_gaz_01','41','গাছা','Gacha',true),
('metro_gaz_02','41','বাসন','Basan',true),
('metro_gaz_03','41','কোনাবাড়ী','Konabari',true),
('metro_gaz_04','41','কাশিমপুর','Kashimpur',true),
('metro_gaz_05','41','পূবাইল','Pubail',true),
('metro_gaz_06','41','টঙ্গী পূর্ব','Tongi East',true),
('metro_gaz_07','41','টঙ্গী পশ্চিম','Tongi West',true),
('metro_gaz_08','41','গাজীপুর সদর মেট্রো','Gazipur Sadar Metro',true),

-- Narayanganj Metropolitan (district 43) — 4 thanas
('metro_nar_01','43','সদর মডেল','Sadar Model',true),
('metro_nar_02','43','বন্দর','Bandar Metro',true),
('metro_nar_03','43','সিদ্ধিরগঞ্জ','Siddhirganj',true),
('metro_nar_04','43','ফতুল্লা','Fatullah',true)
ON CONFLICT (legacy_id) DO NOTHING;