-- Performance indexes for high-traffic tables
CREATE INDEX IF NOT EXISTS idx_sales_shop_created ON public.sales(shop_id, created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_sales_shop_customer ON public.sales(shop_id, customer_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_purchases_shop_created ON public.purchases(shop_id, created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_purchases_shop_supplier ON public.purchases(shop_id, supplier_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_products_shop ON public.products(shop_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_products_shop_name ON public.products(shop_id, lower(name)) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_products_barcode ON public.products(shop_id, barcode) WHERE deleted_at IS NULL AND barcode IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_products_category ON public.products(category_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_customers_shop ON public.customers(shop_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_customers_phone ON public.customers(shop_id, phone) WHERE deleted_at IS NULL AND phone IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_suppliers_shop ON public.suppliers(shop_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_expenses_shop_created ON public.expenses(shop_id, created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_payments_shop_created ON public.payments(shop_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_payments_customer ON public.payments(customer_id) WHERE customer_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_payments_supplier ON public.payments(supplier_id) WHERE supplier_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_cash_shop_created ON public.cash_movements(shop_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_owner_tx_shop ON public.owner_transactions(shop_id, created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_other_income_shop ON public.other_income(shop_id, created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_notifications_user_created ON public.notifications(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_user_unread ON public.notifications(user_id) WHERE is_read = false;
CREATE INDEX IF NOT EXISTS idx_shop_members_user ON public.shop_members(user_id);
CREATE INDEX IF NOT EXISTS idx_shop_members_shop ON public.shop_members(shop_id);
CREATE INDEX IF NOT EXISTS idx_wishlists_shop_created ON public.customer_wishlists(shop_id, created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_wishlist_items_wishlist ON public.customer_wishlist_items(wishlist_id, position);
CREATE INDEX IF NOT EXISTS idx_mp_orders_shop_created ON public.marketplace_orders(shop_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_mp_listings_shop ON public.marketplace_listings(shop_id) WHERE is_published = true;
CREATE INDEX IF NOT EXISTS idx_subscriptions_user_active ON public.subscriptions(user_id, expires_at DESC) WHERE status = 'active';
CREATE INDEX IF NOT EXISTS idx_user_roles_user_role ON public.user_roles(user_id, role);
CREATE INDEX IF NOT EXISTS idx_profiles_phone ON public.profiles(phone) WHERE phone IS NOT NULL;